source "https://rubygems.org"

gem "jekyll", "~> 4.2.1"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.3.0"
  gem "jekyll-sass-converter", :git => "https://github.com/CloudCannon/jekyll-sass-converter.git"
  gem "jekyll-watch", :git => "https://github.com/CloudCannon/jekyll-watch"
  gem "jekyll-postcss-v2", "~> 1.0.1"
  gem "jekyll-archives", "~> 2.2.1"
  gem "jekyll-feed", "~> 0.16.0"
end
